all:
	gcc -o serial serial.c -lm
	gcc -o openmp openmp.c -fopenmp -lm
	gcc -o load_sharing_openmp load_sharing_openmp.c -fopenmp -lm
        gcc -o max_parallelize_openmp load_sharing_openmp.c -fopenmp -lm
